### ISSUE TITLE
Add Landcover Layers

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash#853] opened 2021-03-21 10:17 UTC
Need to add Landcover layers: 
- Urban Atlas 2019 --> can we add the different classes as individual layers in the basemaps?
https://land.copernicus.eu/local/urban-atlas/urban-atlas-2018

- CLC 2018 --> to add as baselayer
https://github.com/sentinel-hub/public-collections/tree/main/collections/corine-land-cover

**Comment by santilland** [comment] 2021-03-23 10:57
I have been trying to add the CLC data from sentinelhub, Grega helped me set it up, it needs to be added as a specific BYOD layer, i will explain the setup to Alessandro or maybe i can actually copy the configuration to his account.
The Problem is Grega said:  
"Note that the layer is only working up to some zoom level, I think 500m/pixel (level=9?)"  
So i am relatively sure we won't see anything load when the map is a little zoomed out, i think this will probably be an issue.

**Comment by santilland** [comment] 2021-03-23 12:30
As for the Urban Atlas, there is already a notebook on EDC that can be used as an example of how to access the data:
https://eurodatacube.com/marketplace/notebooks/contributions/EDC_GeoDB_access_Urban_Atlas_Data_v1.ipynb

**Comment by aapopescu** [comment] 2021-03-25 06:55
Thanks, @santilland! 

> I have been trying to add the CLC data from sentinelhub, Grega helped me set it up, it needs to be added as a specific BYOD layer, i will explain the setup to Alessandro or maybe i can actually copy the configuration to his account. -- OK


> The problem is Grega said:
> "Note that the layer is only working up to some zoom level, I think 500m/pixel (level=9?)"
> So i am relatively sure we won't see anything load when the map is a little zoomed out, i think this will probably be an issue. --- Can you confirm that the issue is for lower zoom levels? We are considering to replace the current "S2GLC LandCover Europe 2017" baselayer with CLC 2018.

**Comment by santilland** [comment] 2021-03-25 09:13
I included CLC2018 layer now, i used it for example for tropomi as base layer:
![image](https://user-images.githubusercontent.com/4036819/112447805-01aece00-8d52-11eb-8432-146ff38a5bda.png)
and this is the first zoom level where data appears:
![image](https://user-images.githubusercontent.com/4036819/112447977-33c03000-8d52-11eb-8751-9194f56396bf.png)
Seems to be at zoom level 8. The default map starts at zoom level 2, so more or less zoom in 6 times until something appears.

**Comment by santilland** [comment] 2021-04-07 13:22
@aapopescu what should we do with the zoom level issue? i am really unsure adding a warning is the best solution, but if you i
think it is we can implement it.

**Comment by lubojr** [comment] 2021-09-10 08:58
Closing for now. Put on Hold

**Closed by lubojr** 2021-09-10 08:58 UTC
Labels: Put on hold
