### ISSUE TITLE
Using Airquality Ozone at city level model, Hamburg is in wrong location

### ISSUE THREAD

**Issue by AlessandroScremin** [eurodatacube/eodash#2527] opened 2024-04-11 15:28 UTC
@lubojr 

Race staging
ui-panels

I see for ozone city model in Hambur is out of region (Russia), Icheched on operational Race dashboard and location os correct.

![image](https://github.com/eurodatacube/eodash/assets/65602207/adc91339-c277-475e-b43a-b80ecd85f3ad)

**Comment by lubojr** [comment] 2024-04-11 15:40
This is data coming from GeoDB in table N1d. Could you please check the aoi field it there?

**Comment by lubojr** [comment] 2024-05-06 09:25
@dmoglioni @AlessandroScremin as a summary, this should be fixed on GeoDB side, because our tooling takes the last row coordinate for a single POI, therefore the incorrect value caused by CAMS data updates error.

**Comment by dmoglioni** [comment] 2024-05-06 11:13
@lubojr A clarification: is this indicator regularly updated or was it just a one-time ingestion? Because I cannot find it on the automated workflows I manage.

**Comment by lubojr** [comment] 2024-05-06 15:54
@dmoglioni No the indicators N1a, N1b, N1c, N1d are not regularly updated anymore. They was one-off ingested as part of migration of original CSVs which were in eodash repo.

**Comment by dmoglioni** [comment] 2024-05-09 11:19
@lubojr Hamburg AOI coordinates have been fixed for N1a/b/c/d, could you please cross-check it? Thanks

**Comment by lubojr** [comment] 2024-05-09 20:07
@dmoglioni Thank you! I have tried a local build and confirm that the Hamburg AOI coordinates generated are correct now. I will re-trigger a catalog build to propagate the geodb update to the production catalog. Closing the issue.

**Closed by lubojr** 2024-05-09 20:07 UTC
Labels: bug, data integration
