### ISSUE TITLE
Loading 2 elements on custom dashboard blocks the application

### ISSUE THREAD

**Issue by eodash-issues** [eurodatacube/eodash#1755] opened 2022-11-14 15:33 UTC
<h3 id="environment">Environment</h3>
<p><strong>App version:</strong> 4.0.0</p>
<p><strong>Current URL:</strong> <a target="_blank"  href="https://race.esa.int/?x=1280174.14412&amp;y=7332148.83319&amp;z=4.46184">https://race.esa.int/?x=1280174.14412&amp;y=7332148.83319&amp;z=4.46184</a></p>
<p><strong>Operating system:</strong> MacOS</p>
<p><strong>Affected browser:</strong> Chrome 105</p>
<h3 id="steps-to-reproduce">Steps to reproduce:</h3>
<p>Added two instances from a global map indicator. Custom dashboard is blocked on &quot;loading&quot; and the application is not responding. Thus, it is not possible to &quot;Discard the custom dashboard&quot; and this remains cached, so that on the next session in the same browser the application loads with the last custom dashboard still active. </p>
<h3 id="expected-behaviour">Expected Behaviour:</h3>
<p>When page is closed the last custom dashboard is cleared. </p>
<h3 id="contact-information-or-additional-comments-optional-publicly-visible">Contact information or additional comments (optional, publicly visible):</h3>
<p>Anca</p>

**Comment by silvester-pari** [comment] 2022-11-15 08:16
Hello @aapopescu and thanks for reporting, I currently can't reproduce this issue with a fresh browser; however, it could be that switching between the brands (RACE, eodashboard) confuses the custom dashboards a bit since indicators are only present in one of the brands. Could you try this with a new browser instance?

Generally, clearing the custom dashboard on browser close is currently not intended, as the user would loose the progress being made (by either closing the browser by mistake or the browser crashing). However, we can implement an always-there "discard" button for the fringe cases that there is an issue loading a custom dashboard.

**Comment by silvester-pari** [comment] 2022-11-16 14:26
Confirmed now, happens e.g. with `FR9-E13b`

**Closed** 2022-11-29 16:23 UTC
Labels: bug
