### ISSUE TITLE
Water Quality Maps and timeseries changes

### ISSUE THREAD

**Issue by AlessandroScremin** [eurodatacube/eodash#2293] opened 2023-07-24 10:06 UTC
Dear @lubojr @santilland 

I received some feedback from CNR about water quality maps and Timeseries:

- description panel on the right:
  - Danube Delta:
  - - Remove Section "SST during Covid-19 lockdown" in 'Sea Surface Temperature: Sea Surface Temperature Anomaly Regional Maps - Multi-sensor product'
  - - Remove Section "Examples of the impact of COVID-19 on Water Quality" in 'Total Suspended Matter: Water Quality Regional Maps - Multi-sensor product'
  - - Remove Section "Examples of the impact of COVID-19 on Water Quality" in 'Chlorophyll-a concentration: Water Quality Regional Maps - Multi-sensor product'

- Water quality timeseries chart. Need to be updated. I think it is due to change in the table name in the geoDB. It was done for trilateral but not for the race.esa.int
- from N3 to "Regional_Water_Quality_Europe_timeseries"

feature to be added
- Add  the Chl-a concentration (point) - Water Quality Time Series from the .csv
-  Add the SST (point) - Time Series from the .csv

the last two should be the feature from which on the point in the timeseries chart you get aceess to the related MAP. I think it was a task under implementation.

**Comment by lubojr** [comment] 2023-07-24 14:03
Data related changes have been just pushed to staging.

The last point is a useful feature requested in both GTIF and race/trilateral contexts and tracked here. https://github.com/eurodatacube/eodash/issues/1735

I will therefore close the issue.

**Comment by AlessandroScremin** [comment] 2023-07-24 15:09
Sorry for that @lubojr , need to reopen the ticket
I noticed that timeseries of water quality are missing on the Danube delta AOI (whereas Maps are available). Timeseries and Danube delta AOI (RO1) are avaialve in the geoDB.

Other story for SST Sea_Surface_Temperature_Timeseries. They are completely missing in the race.esa.int dashbaord
geoDB table name is "Sea_Surface_Temperature_Timeseries"

**Comment by lubojr** [comment] 2023-07-24 15:41
@AlessandroScremin I have added this table to be referenced by race client, but in addition to the SST indicator POIs, following change happened:
Each current N3 indicator entry now has intertwined entry from the SST dataset as well. This seems like data are duplicated in the table Sea_Surface_Temperature_Timeseries once with indicator code N3 and once with SST, while it should be only SST. Could you please check? Thanks
![image](https://github.com/eurodatacube/eodash/assets/19269667/7c27c992-78ac-4197-a16e-32dacf104ddf)

**Comment by AlessandroScremin** [comment] 2023-07-25 06:28
@lubojr 
the POIs for N3 and SST are the same (4 POIs), as the areas analyzed are the same. So what you mean as duplicated?

**Comment by lubojr** [comment] 2023-07-25 07:38
Aha, sorry, not really exactly duplicates as I originally thought from our export script.

I have double checked the table "Sea_Surface_Temperature_Timeseries" directly and entries until time=2023-01-12T07:55:17 have indicator_code=N3 while all the entries after this time have indicator_code=SST

All entries should have indicator_code=SST, because we have indicator_code N3 for data with water quality (chlorophile).

**Comment by AlessandroScremin** [comment] 2023-07-25 12:58
should be already fixed @lubojr

**Comment by lubojr** [comment] 2023-07-25 13:18
It does not seem to be:
```python
indicator_data = geodb.get_collection("Sea_Surface_Temperature_Timeseries",database='eodash')

print(len(indicator_data[indicator_data["indicator_code"].isin(["N3"])]))
# 816
print(len(indicator_data[indicator_data["indicator_code"].isin(["SST"])]))
# 124
```
Could you please double check?

**Comment by lubojr** [comment] 2023-07-26 14:28
> It does not seem to be:
> 
> ```python
> indicator_data = geodb.get_collection("Sea_Surface_Temperature_Timeseries",database='eodash')
> 
> print(len(indicator_data[indicator_data["indicator_code"].isin(["N3"])]))
> # 816
> print(len(indicator_data[indicator_data["indicator_code"].isin(["SST"])]))
> # 124
> ```
> 
> Could you please double check?

@AlessandroScremin I have just checked now and I still get these results.

**Comment by AlessandroScremin** [comment] 2023-07-26 15:52
@lubojr 
You are right..it seems we have to fix with our automatic ingestion...now should be fixed again.

**Comment by AlessandroScremin** [comment] 2023-07-27 13:11
@lubojr 
it seems the replace command I used didn't write the change...
now should be fine

Alessandro

**Comment by lubojr** [comment] 2023-07-28 07:41
@AlessandroScremin Thank you, I can confirm that the indicator_code discrepancy has been fixed and data are updated in staging.
Could you please also ask CNR if the used chart visualisation is fine? I used the exactly same one as in chlorophyle charts except for the logarithmic scale.

The map -> chart -> map time interaction has been implemented in https://github.com/eurodatacube/eodash/pull/2294 and is waiting for a review to be merged to staging.

**Comment by lubojr** [comment] 2023-08-03 13:55
Last remaining point (merge SST and N3 charts with map indicators) is tracked here. https://github.com/eurodatacube/eodash/issues/2301

**Closed by lubojr** 2023-08-03 13:55 UTC
Labels: enhancement, data integration
