### ISSUE TITLE
Ingestion of CCI datasets (ZARR)

### ISSUE THREAD

**Issue by AlessandroScremin** [eurodatacube/eodash#1231] opened 2022-02-09 08:02 UTC
@gunbra32 @aapopescu @santilland 
cc: @dmoglioni @Schpidi 

We have a list of CCI datasets that we need to present in the EO Dashboard, some of which may already be available in the EDC, and most of the data is already available as zarr.

We would need your team's help to: 
1) check if all the data we need is already in EDC - from Philippe I understand ideally all of it should be 
2) add any missing data 
3) help with any eventual data transformation so that it can be visually presented on the dashboard 

Here follow the list of datasets needed for the Dashboard

- [x] NPP (1998-2020): https://catalogue.ceda.ac.uk/uuid/69b2c9c6c4714517ba10dab3515e4ee6
- [x] Envisat Sea Ice: https://catalogue.ceda.ac.uk/uuid/f4c34f4f0f1d4d0da06d771f6972f180
- [x] Cryosat-2 Sea Ice: https://catalogue.ceda.ac.uk/uuid/ff79d140824f42dd92b204b4f1e9e7c2
- [ ] Before 2017: https://cds.climate.copernicus.eu/cdsapp#!/dataset/satellite-sea-ice-thickness?tab=overview

So we would need to check what is already in the EDC, and thus for the ones that are missing to discuss the HOW TO approach for the ingestion of the missing datasets: Via ZARR format or COG Geotiff 

Thnaks for the collaboration

Alessandro

PS @gunbra32 please feel free to add to the conversation any contact person will work on this from your side

**Comment by gunbra32** [comment] 2022-02-09 11:17
Hi Alessandro, 

Please add [@TonioF](https://github.com/TonioF) to this issue. 

We will check the availability of the data. It is still a bit unclear to me, what are you referring to when wirting "ingestion". I guess you are referring to Sentinel Hub. Do you need a WMTS or raw data or anything else?

**Comment by AlessandroScremin** [comment] 2022-02-09 12:22
@gunbra32 (and Tonio that I dont know why, I can not tag him in the conversation @TonioF)
Dear Gunnar 
yes ingestion for me means via Sentinel Hub. All the layers and dataset I manged have been ingested into Sentinel Hub as COG geotiff files.

Here it depends how we would proceed, in the sense that I didn't handle ZARR into EDC before, so we need your support to udnerstand if the ZARR format via CCI/Ceda is already compliant with EDC ZARR requirements:
if yes then should be better to go with the ZARR (and hence your support is needed,  and if so it is the  reccomended approach)
If not ZARR compliant then I could proceed as usual and download the net cdf files, convert them in COG (make some validation on the format, no data values, values) and then ingest them in Sentinel Hub

In the second case I can manage the process by myself.
Of course if the data are avaialbe in ZARR and already compliant with EDC requirments, then I would you go by using the ZARR.

Let me know what your opinion on that.

Alessandro

**Comment by gunbra32** [comment] 2022-02-09 12:27
When you write " avaialbe in ZARR and already compliant with EDC requirments", are you referring to SH again? The background is here that we invested some effort to generate these zarrs from netcdf to make them compliant with xcube. So, we could serve these data directly rather than converting data from NetCDF to zarr to COG just to serve them as WMS. 

Eventually, it is of course your decision how to tackle this task and we will try to help as good as possible.

**Comment by AlessandroScremin** [comment] 2022-02-09 12:43
@gunbra32 @tonioF @aapopescu @santilland 

If they are already availabe in ZARR and in ready for xcube, then I would proceed as follow:

- Check the avaialbility as checklist in comments above (@gunbra32 @TonioF)
- made ready  for the Dashboard the data already available (@gunbra32 @santilland)
- Missing data: to open a discussion with @aapopescu @gunbra32 @santilland and me to understand how to proceed.

kr

Alessandro

**Comment by TonioF** [comment] 2022-02-10 08:33
Of the datasets listed above, Cryosat-2 SEAICE has already been converted to zarr, the others haven't. As the Envisat SEAICE dataset is very similar in structure, the effort to convert it to zarr would be relatively low.

**Comment by AlessandroScremin** [comment] 2022-02-11 15:08
@TonioF  cc: @aapopescu @dmoglioni 
So I would suppose that you will made available for the dashboard 
Cryosat 2 SeaIce
Envisat SeaIce

and I will create COG files for the:
NPP

@TonioF do you think datasets of seaIce before 2017 are so different from the Other seaIce datasets?

@santilland what you think should be best for you? TO have all in ZARR from Brockman or,  in case of too much effort from their side, could you retrieve some data from them in ZARR e the otherd as usual as EDC layers ID COG file?

**Comment by TonioF** [comment] 2022-02-14 08:22
We run our ZARR conversion on JASMIN, where also the CEDA data is hosted (and eventually the ZARR files we currently have, too). For the other SEAICE datasets we'd have to set up a conversion infrastructure first, which would be a hassle.

BTW, regarding the fourth dataset, are you really interested in SEAICE before 2017? That should be covered by the Envisat and Cryosat2 datasets.

**Comment by santilland** [comment] 2022-02-14 10:10
@AlessandroScremin you asked:
what you think should be best for you? TO have all in ZARR from Brockman or, in case of too much effort from their side, could you retrieve some data from them in ZARR e the otherd as usual as EDC layers ID COG file?

For the eodashboard we currently use the SH WMS service to visualize the data and the SH FIS service to show statistical information on the data. For this we have been provided a layer identifier for a "visual" layer (for use with WMS) and a "raw" layer to retrieve the statistical information.

As long as these two service endpoints can be used we have no further requirements, so whatever data formats, storage options, etc allows using these endpoints is fine with us.

**Comment by AlessandroScremin** [comment] 2022-02-14 10:50
@santilland 
and what about Europe, CMEMS Water Quality ?
I didn't ingest it into EDC or SH, so I uderstood they came out from Brockman in ZARR, am I missing something?

Ale

**Comment by santilland** [comment] 2022-02-14 10:56
@AlessandroScremin 
The CMEMS water quality (N3c) is accessed per WMS interface and does not have access to statistical data information.
The WMS endpoint is serviced by a THREDDS server:
nrt.cmems-du.eu/thredds/wms
not sure if this is provided by Brockman

**Comment by AlessandroScremin** [comment] 2022-02-14 13:40
@santilland @TonioF  cc: @aapopescu @dmoglioni @
I think we need to call a meeting to understand how the zarr convereted files can be made accessible to the dashboard.
I understood it should be nice to use the CCI ZARR files, but we or at Least Myself, need to undestand how EOX can access the ZARR files. 
From my udnerstanding, so far we made availabe the several indicaotrs in 4 ways:

- COG file ingested via EDC (for which EOX can retrieve also statistics) via SH WMS
- direct WMS from web servers
- Time series via csv --> GeoDB
- GEopackage (truck indicaotr)

So where and how we could use ZARR?

hope this calrify the point: what we really need to make those datasets availabe into the dashboard? If ZARR is not the best approach, then I can proceed as usual converting nc files into COG and ingest them into EDC. Till now I worked in this way, and I never ingested ZARR into EDC, so any solution with ZARR shoudl fall in the four methods above or something ELSE you @tonioF and @santilland  should agree. 

Alessandro

**Comment by santilland** [comment] 2022-02-14 16:04
I do not have the insights on what data is supposed to be available where in what format, but ZARR is a data format conceptually as is COG. In order to visualize it on the dashboard we need it to be rendered somewhere. 
My understanding is there is a way to import ZARR data into EDC SH (https://docs.sentinel-hub.com/api/latest/api/zarr/) more or less equivalent to importing COG data (so in principle as the first point you describe Alessandro).
Once the data is imported it is probably possible to configure visualization and data layers accessible through WMS and FIS api?
If i understood previous communication correctly someone is responsible to making all of this data available through (EDC) SH, so i guess it needs to be ingested there one way or the other? Probably using the ZARR data format as the CCI data is provided like that?
I am happy to attend a meeting if you think i can provide any further information.

**Comment by TonioF** [comment] 2022-02-15 16:11
I would not object to a meeting, but I am not sure it is really required. I am not familiar with the ingestion of data into the SH, so I cannot really comment on this. What I can do is to say how the two SEAICE datasets in ZARR format can be accessed, as they are stored in a publically accessible s3 bucket. Also, in case you might not be familiar with it, they are also accessible from the ODP via WMS:
- https://data.cci.ceda.ac.uk/thredds/wms/esacci.SEAICE.mon.L3C.SITHICK.RA-2.Envisat.NH25KMEASE2.2-0.r1?service=WMS&version=1.3.0&request=GetCapabilities 
- https://data.cci.ceda.ac.uk/thredds/wms/esacci.SEAICE.mon.L3C.SITHICK.SIRAL.CryoSat-2.NH25KMEASE2.2-0.r1?service=WMS&version=1.3.0&request=GetCapabilities

There is unfortunately no WMS for the NPP data, however, that could also be converted to ZARR with relative ease and put into the s3 bucket.

**Comment by gunbra32** [comment] 2022-02-16 09:17
I think the main misunderstanding is that EDC is not equal to SH. There are generally two ways how we can provide access to CCI data 
1. CCI Open Data Portal -> xcube-cci store (or xcube Generator) -> zarr
2. (rather new) nc -> zarr on Jasmin OBS (see Tonios comment above)

Then, optionally, we can provide a WMTS for these data generated by xcube, which you can integrate to your favourite application or you use CEDA's WMS right away. In case you require SH, however, you will have to ingest the data there. 

So, we suggest the following: 

1. you have a look at the available zarrs (@TonioF to provide the url, please)
2. If that works for you, we also convert the NPP to zarr and make them available there. 
3. we have a look into the CDS data. No idea, however,  how SH handles the Lambert Azimuthal Equal Area projection.

**Comment by TonioF** [comment] 2022-02-16 13:22
As I've said, the ZARRs may be accessed via s3. The endpoint url is https://cci-ke-o.s3-ext.jc.rl.ac.uk:443/ , the bucket name is 'esacci'. The names of the ZARR datasets are 'ESACCI-SEAICE-L3C-SITHICK-RA2_ENVISAT-NH25KMEASE2-2002-2012-fv2.0.zarr' and 'ESACCI-SEAICE-L3C-SITHICK-SIRAL_CRYOSAT2-NH25KMEASE2-2010-2017-fv2.0.zarr', respectively.

**Comment by gmilcinski** [comment] 2022-02-18 07:40
@Kampen1988 @Dorothyrono - can someone in your team check the ZARR datasets mentioned [above](https://github.com/eurodatacube/eodash/issues/1231#issuecomment-1041486576) and see, whether they fit [constraints for ingestion in zarr using BYOD](https://docs.sentinel-hub.com/api/latest/api/zarr/#data-constraints). 

And, along the way, ingest it as a test colleciton,

**Comment by sh-vas** [comment] 2022-02-21 11:05
> 

@TonioF is there a specific access method to this bucket? I am trying to access the ZARRS but I get the following error from s3:

```
The AWS Access Key Id you provided does not exist in our records
```

Do I need specific credentials?

**Comment by TonioF** [comment] 2022-02-21 14:32
There are no special credentials required. Depending on how you try to access the bucket, you might need to set 'anonymous' parameters to True.

**Comment by gmilcinski** [comment] 2022-02-22 15:39
We have checked the zarr (ESACCI-SEAICE-L3C-SITHICK-RA2_ENVISAT-NH25KMEASE2-2002-2012-fv2.0.zarr) and we cannot support it with "Bring your own zarr" of the Sentinel Hub for the moment. The constraint that failed at the moment is that it is 2-dimensional (we only support 1-dimensional zarrs at the moment).  

To use it in Sentinel Hub, we would either have to:  
- extend BYOD capability to support multi-dimension zarrs (several man-weeks of work)
- convert zarrs so that they fit the existing [data constraints](https://docs.sentinel-hub.com/api/latest/api/zarr/#data-constraints)

**Comment by gunbra32** [comment] 2022-02-22 16:28
That's a pity. Not sure I understand the dimensionality constraint, though. Following the link above, you are able to ingest 2-D and 3-D variables with x/y, lat,/lon, and time as dimensions. Is this correct? 

I suggest three things: 
1) We can look into the changes required to meet SH specifications, if SIN could specify the dimensionality issue a bit better. 
2) EOX may try to integrate an xcube WMTS into the dashboard, just in case this will be required (https://edc-api.brockmann-consult.de/api/) 
3) In the meantime, we had been discussing with STFC UKRI and they offered to support the direct integration of their WMS into the dashboard. This would be my preferred solution, at least for the variables without the need for the SH statistical services. Can EOX identify these variables?

**Comment by TonioF** [comment] 2022-02-23 09:23
I guess the issue is that the SEAICE datasets' coordinates are provided in Lambert Azimuthal Equal Area projection and that there are both xc/yc and lat/lon coordinates. Is that right?

**Comment by sh-vas** [comment] 2022-02-23 20:54
The problems we had to ingest the ZARR files using Sentinel Hub are the following:

- `lat` and `lon` arrays have 2 dimensions
- `xc` and `yc` have 1 dimension, which would be the correct format for ingestion in SH
- `xc` and `yc` are in  Lambert Azimuthal Equal Area which is not supported by Sentinel Hub, unless it is EPSG:3035
- `lat-lon` "grid" encoded in the lat and lon arrays isn't an equidistant rectangular grid, so we can't ingest it as WGS84 either
- there is no `CRS` attribute or information in the zarr

All of these combined make the ingestion complicated. However, a couple of small tweaks to the data would allow the use of Sentinel Hub I believe.

**Comment by TonioF** [comment] 2022-02-24 08:31
The SEAICE data is projected in EPSG:6931 . The CRS information is given in the ENVISAT dataset in the 'Lambert_Azimuthal_Grid' variable.

**Comment by gunbra32** [comment] 2022-02-24 14:11
Sorry for the incomplete url for the WMTS above, try this one: 

https://edc-api.brockmann-consult.de/api/wmts/1.0.0/WMTSCapabilities.xml

**Comment by TonioF** [comment] 2022-02-24 14:34
We have now also converted the NPP dataset. It is available in the s3 store as BICEP-OC-L3S-PP-MERGED-1M_MONTHLY_9km_mapped-1998-2020-fv4.2.zarr . As it uses EPSG:4326, I think there should not be any problems with this one.

**Comment by Schpidi** [comment] 2022-02-25 12:28
Thanks @TonioF!

@sh-vas could you please try to ingest this NPP ZARR and let us know once available so we could test accessing it from the dashboard? Thanks

**Comment by Schpidi** [comment] 2022-03-03 15:50
@maximlamare from our call earlier today I understand you successfully ingested the NPP data. Could you share the link to the data with us presumably via some private channel so that we can start testing from the dashboard side? Thanks.

**Comment by sh-vas** [comment] 2022-03-03 15:51
We have looked into the ingestion of the NPP zarr. It is compatible with SH services with the following modifications:

- we had to remove `latitude` and `longitude` arrays because SH reads `lat` and `lon` as 1D arrays but all other datasets need to be 2D or 3D.
- the chunking in the zarr you provided is too big for our renderers and causes problems. We rechunked the zarr to (1, 1080, 1080) and it works fine.

@Schpidi mentioned that we should share the access, should it be communicated here or privately?

**Comment by sh-vas** [comment] 2022-03-03 15:51
Same time...

**Comment by Schpidi** [comment] 2022-03-08 13:51
@gunbra32 @TonioF do you have any recommendations on the visualization? This is a first test request resulting in the below. Thanks.

`?service=WMS&request=GetMap&layers=PP&styles=&format=image%2Fpng&transparent=false&version=1.1.1&warnings=true&evalscript=Ly9WRVJTSU9OPTMKCmZ1bmN0aW9uIHNldHVwKCkgewogIHJldHVybiB7CiAgICBpbnB1dDogWyJwcCJdLAogICAgb3V0cHV0OiB7IGJhbmRzOiA0IH0KICB9Owp9CgpmdW5jdGlvbiBldmFsdWF0ZVBpeGVsKHNhbXBsZSkgewogIHJldHVybiBzYW1wbGUucHAgPCAxMDAwMAogICAgPyBbc2FtcGxlLnBwLzEwMDAsc2FtcGxlLnBwLzEwMDAsIHNhbXBsZS5wcC8xMDAwLCAxXQogICAgOiBbMCwwLDAsMF0KfQ%3D%3D&width=512&height=512&srs=EPSG%3A3857&bbox=10018754.171394622,-10018754.171394622,20037508.342789244,0`

![image](https://user-images.githubusercontent.com/482265/157250309-2afc092b-3859-4f77-9d7e-3e8853ffce63.png)

**Comment by TonioF** [comment] 2022-03-09 13:10
Not quite sure what you ask for. Do you want a recommendation for a color scale?

**Comment by Schpidi** [comment] 2022-03-09 13:28
The requirement for us is to visualize the NPP data on the RACE dashboard. I understand you're the experts for the data. Thus I'm asking what visualization would be best to use.

**Comment by TonioF** [comment] 2022-03-11 09:05
The best color scheme to use for this dataset would be matplotlib's default 'jet' scheme, scaled from 0 to 4000. The image belows is scaled linearly, but it would be optimal to use logarithmic scaling.

![image](https://user-images.githubusercontent.com/1598254/157836053-b7e7bc9c-62a0-4e03-b440-0dadee09200d.png)

**Comment by sh-vas** [comment] 2022-03-11 13:01
@Schpidi I updated the WMS layer to match @TonioF 's recommendation.

**Comment by santilland** [comment] 2022-03-16 16:22
Thanks to the support of Maxim vie email we were able to check that the WFS and WMS functions can be used as previously for data integrated through Zarr.
The FIS api does not support data ingested as zarr. The new statistical API neither, but as far as i understood this will be implemented.
As we can use WMS and WFS and at some point also the new statistical API i think the other 3 datasets listed can be also ingested.

**Comment by Schpidi** [comment] 2022-03-17 16:52
@sh-vas could you please add another layer for the NPP data with a purple to red colorbar, similar to the plot below? Thanks

![AnnualMean2020](https://user-images.githubusercontent.com/482265/158852451-32c8863f-737a-438c-9368-cf38a220fdfc.png)

**Comment by maximlamare** [comment] 2022-03-18 08:39
@Schpidi do you have a reference for this colorbar? Or even better: a list of values?

Otherwise I can easily implement one of the following (maybe `turbo`):

![overview](https://user-images.githubusercontent.com/32132761/158965751-ee880d55-9268-4bf0-8b92-c3e779d0e742.png)

**Comment by Schpidi** [comment] 2022-03-18 09:14
@maximlamare I'm afraid I don't have more information. let's take your proposed one and see what the scientists say. thanks

**Comment by maximlamare** [comment] 2022-03-18 11:34
Does this seem ok to you?

https://services.sentinel-hub.com/ogc/wms/0a25fa27-f880-42ad-967d-cee3fd83fb6e?REQUEST=GetMap&CRS=CRS:84&BBOX=-47.912321,-51.944265,-7.335891,48.107431&LAYERS=PP2&WIDTH=390&HEIGHT=1458&FORMAT=image/jpeg&TIME=2000-12-01/2022-03-18


![660caac9-8247-472a-8b1d-fc4983cf03ad](https://user-images.githubusercontent.com/32132761/158995963-3ac59fc0-0858-4402-a041-58c7e0d5f7fd.jpeg)

**Comment by AlessandroScremin** [comment] 2022-03-18 11:52
THis one or Jet...maybe a bit more transition from one color to the other...
But we could show 1 (turbo) or 2 (Jet) samples to the scientist...and see what they think...

**Comment by maximlamare** [comment] 2022-03-18 14:31
> The FIS api does not support data ingested as zarr. The new statistical API neither, but as far as i understood this will be implemented.

The new Statistical API now supports zarr! I have sent an example to @santilland via email.

**Comment by AlessandroScremin** [comment] 2022-03-22 11:18
@TonioF  @gmilcinski @maximlamare @Schpidi @gunbra32 

Do you have any updates on the status of the following datasets?

Here follow the list of datasets needed for the Dashboard

- [ ] NPP (1998-2020): https://catalogue.ceda.ac.uk/uuid/69b2c9c6c4714517ba10dab3515e4ee6
- [ ]  Envisat Sea Ice: https://catalogue.ceda.ac.uk/uuid/f4c34f4f0f1d4d0da06d771f6972f180
- [ ]  Cryosat-2 Sea Ice: https://catalogue.ceda.ac.uk/uuid/ff79d140824f42dd92b204b4f1e9e7c2
- [ ]  Before 2017: https://cds.climate.copernicus.eu/cdsapp#!/dataset/satellite-sea-ice-thickness?tab=overview
 
 SO I understand that NPP is fine now
 
 What about the SeaIce collections?
 
 kr
 
 Alessandro

**Comment by aapopescu** [comment] 2022-03-22 11:19
> @TonioF @gmilcinski @maximlamare @Schpidi @gunbra32
> 
> Do you have any updates on the status of the following datasets?
> 
> Here follow the list of datasets needed for the Dashboard
> 
> * [x]  NPP (1998-2020): https://catalogue.ceda.ac.uk/uuid/69b2c9c6c4714517ba10dab3515e4ee6
> * [ ]   Envisat Sea Ice: https://catalogue.ceda.ac.uk/uuid/f4c34f4f0f1d4d0da06d771f6972f180
> * [ ]   Cryosat-2 Sea Ice: https://catalogue.ceda.ac.uk/uuid/ff79d140824f42dd92b204b4f1e9e7c2
> * [ ]   Before 2017: https://cds.climate.copernicus.eu/cdsapp#!/dataset/satellite-sea-ice-thickness?tab=overview
> 
> SO I understand that NPP is fine now
> 
> What about the SeaIce collections?
> 
> kr
> 
> Alessandro

Cc: @sh-vas

**Comment by sh-vas** [comment] 2022-03-22 21:31
If the other datasets are provided in the correct format (as explained in this thread) and re-chunked, then we can ingest them.

**Comment by aapopescu** [comment] 2022-03-22 23:10
Dear @TonioF , can you please support the preparation of the Zarr files for the sea ice product above? Thank you!
Cc: @gunbra32

**Comment by TonioF** [comment] 2022-03-23 09:30
My understanding was that the NPP data was fine, too. @sh-vas , do you need us to make the adjustments according to your post? If so, can you give us a number what is the max size that the chunking should have?

With respect to the SEAICE data: We have added the CRS information. However, we seem to be stuck with the two issues: 
- The lat and lon arrays are two-dimensional and non-equidistant, therefore not usable
- The xc- and yc- arrays are given in a CRS that is not supported by Sentinel Hub

I don't see how this could be fixed by a small tweaks (https://github.com/eurodatacube/eodash/issues/1231#issuecomment-1049207313).

**Comment by sh-vas** [comment] 2022-03-23 10:22
The NPP worked well. 

For the chunking, we recommend to do 1x1080x1080 (3072 is officially supported but it causes sluggish responses). Tests have shown that a time chunking of 1 is optimal.

The comments on the limitations of the sea ice sets are correct unfortunately. I'm guessing a reprojection is too complex?

**Comment by TonioF** [comment] 2022-03-24 07:55
I will try to reproject the SEAICE data to one of the supported CRS.

**Comment by santilland** [comment] 2022-03-28 14:25
For now we have tested the NPP data on some provided SH Instance, where the interfaces work as expected.
Now, if i am not mistaken, someone would need to transfer the layers (or copy / or create?) to the SH instance controlled by @AlessandroScremin . I imagine the data itself does not need to be moved.
So currently the NPP layers are in the instance starting with 0a25fa27-....
And this configuration should be copied to the instance starting with 0635c213- ....
Not sure if i should write full instance ids in issues (let me know if you need the information).
Can this layer moving/copying be done by Alessandro? What information would he need to be able to do it? If not who could take care of doing it?

As for the 4 datasets listed we are under quite a tight schedule in order to be able to incorporate them into the stories release. The currently planned deadline to have things ready is 15th of April. Taking into account we would also need some time to incorporate the data into the dashboard and then link the information to the stories and respective content creation and design.
What datasets do you think could be ready by the end of this week?
Do you see it as realistic for all 4 datasets to be ready by the end of next week (8th of April)?

**Comment by AlessandroScremin** [comment] 2022-03-29 06:55
@santilland 
I can't see that NPP collection among the ones I managed, so I think it has to be shared with me or directly with the ID that owns   the instance starting with 0635c213- ....

**Comment by TonioF** [comment] 2022-03-30 09:48
Making good progress with the SEAICE data, so I'm confident we'll have this ready this week. I'll reproject it to EPSG:3995, as that is most similar to the original crs.

**Comment by sh-vas** [comment] 2022-03-30 12:48
> @santilland I can't see that NPP collection among the ones I managed, so I think it has to be shared with me or directly with the ID that owns the instance starting with 0635c213- ....

We are in the process of transferring the instances to @AlessandroScremin . Will let you know when done.

**Comment by santilland** [comment] 2022-03-30 13:13
Great! Thank you!

**Comment by TonioF** [comment] 2022-03-31 17:35
There are new datasets ESACCI-SEAICE-L3C-SITHICK-SIRAL_CRYOSAT2-NH25KMEASE2-2010-2017-fv2_repro.zarr and ESACCI-SEAICE-L3C-SITHICK-RA2_ENVISAT-NH25KMEASE2-2002-2012-fv2_repro.zarr in the s3 store. The EPSG is 3995 (Arctic Polar Stereographic) and the time chunking is 1. Please let me know if you can work with this.

**Comment by sh-vas** [comment] 2022-03-31 20:21
@AlessandroScremin , Dorothy tells me that you have the ZARR ingested as a collection, as well as the configuration layers in your account. Could you check and see if it's all ok please?

**Comment by AlessandroScremin** [comment] 2022-04-01 06:42
@sh-vas  @Dorothyrono 

Dears, I can see the ZARR BICEP collection and the 4 configuration layers in the sentinel hub dashboard, but I can not see the data on the eo-broswer.  There is some specific option to enable on eo-browse side?

![image](https://user-images.githubusercontent.com/65602207/161208943-b1fc4cb2-0dbf-4a80-a51b-e56e880188ec.png)

I already passed the configuration to EOX for calling through the dashboard anyway.

kr

ALessandro

**Comment by AlessandroScremin** [comment] 2022-04-04 08:57
> @AlessandroScremin , Dorothy tells me that you have the ZARR ingested as a collection, as well as the configuration layers in your account. Could you check and see if it's all ok please?

DEAR  @sh-vas @Dorothyrono 

I was able to access only the BICEP NPP layers, i can't see the seaice... did you already shared them with my account?

kr

Alessandro

**Comment by sh-vas** [comment] 2022-04-04 08:58
@AlessandroScremin the activity is ongoing. I will update you when available.

**Comment by sh-vas** [comment] 2022-04-04 09:34
> @sh-vas @Dorothyrono
> 
> Dears, I can see the ZARR BICEP collection and the 4 configuration layers in the sentinel hub dashboard, but I can not see the data on the eo-broswer. There is some specific option to enable on eo-browse side?
> 
> ![image](https://user-images.githubusercontent.com/65602207/161208943-b1fc4cb2-0dbf-4a80-a51b-e56e880188ec.png)
> 
> I already passed the configuration to EOX for calling through the dashboard anyway.
> 
> kr
> 
> ALessandro

I have been told that this will be fixed this week.

**Comment by TonioF** [comment] 2022-04-07 15:59
I checked the dataset again and It looks to me as if some of the extreme coordinate values may be invalid. Can you try to make a subset where you only use values from x- and y-coordinates between indexes 120 and 320?

**Comment by sh-vas** [comment] 2022-04-08 14:12
This got rid of the issue I mentioned above, but we are experiencing some problems with the `EPSG: 3995` at the moment. It's in discussion within the technical team and I will get back to you.

**Comment by sh-vas** [comment] 2022-04-14 09:53
@TonioF would it be possible to reproject the Zarr files to a different EPSG? I have just been made aware that Sinergise have clarified the guidelindes for ZARR data: https://docs.sentinel-hub.com/api/latest/api/zarr/#data-constraints.

> The projection needs to be one of: WGS84 (EPSG:4326), WebMercator (EPGS:3857), any UTM zone (EPSG:32601-32660, 32701-32760), or Europe LAEA (EPSG:3035).

**Comment by TonioF** [comment] 2022-04-20 09:35
I'll try.

**Comment by Schpidi** [comment] 2022-04-20 15:24
Thanks for keeping pushing for this! Please note that May 2nd would be the already postponed deadline to have this data integrated.

**Comment by TonioF** [comment] 2022-04-22 08:15
Okay, this time it worked better (I used the already reprojected data as source). The SEAICE datasets are now available in WGS84 as ESACCI-SEAICE-L3C-SITHICK-SIRAL_CRYOSAT2-NH25KMEASE2-2010-2017-fv2_4326.zarr and ESACCI-SEAICE-L3C-SITHICK-RA2_ENVISAT-NH25KMEASE2-2002-2012-fv2_4326.zarr, repectively. I'll delete the datasets in EPSG:3995 soon, if no one objects.

**Comment by sh-vas** [comment] 2022-04-22 14:13
CRYOSAT and ENVISAT have now been successfully ingested. I will communicate the details to @Schpidi by email for the next steps.

**Comment by AlessandroScremin** [comment] 2022-04-26 12:11
@santilland cc: @aapopescu
I got the visualisation layers for Cryosat adn Envisat Sea Ice THickness.
The visualisation layers have been made avaialbe in the DAshboard COnfiguration layer.
The layers name are:
<html>
<body>


VIS_CRYOSAT_seaIceThickness | ID: VIS_CRYOSAT_SEAICETHICKNESS |  
-- | -- | --
VIS_ENVISAT_SeaIceThickness | ID: VIS_ENVISAT_SEAICETHICKNESS


</body>
</html> 

let me know if its working from your side
Alessandro

**Comment by santilland** [comment] 2022-04-27 10:08
Great news! Thank you all for the work and getting things ready. So as far as I understand we have now at least 3 of the 4 datasets posted initially, i have marked them as checked.
I am not completely sure what the "Before 2017" dataset means. Is this part or integrated in one of the 3 datasets we already have? Then i guess we could close this ticket. 
Or is a separate dataset? Then this would need to be integrated?

**Comment by TonioF** [comment] 2022-04-28 07:07
From what I see, the information in the "Before 2017" dataset should be fully covered by the other two SEAICE datasets. I'll try though to provide this data (and make it possible to get the data after 2017, which is not covered by the other datasets).

**Comment by santilland** [comment] 2022-05-04 09:33
Hello @TonioF my understanding is also that the "Before 2017" is covered by the other two datasets so i think we can close this ticket now if there are no other comments or considerations.

**Comment by TonioF** [comment] 2022-05-09 15:27
The CDS data seems to have different flags, but the sea ice thickness data variables are the same.

**Closed** 2022-05-09 15:35 UTC
Labels: enhancement
