### ISSUE TITLE
data not loading

### ISSUE THREAD

**Issue by eodash-issues** [eurodatacube/eodash#2665] opened 2024-09-09 14:54 UTC
<h3 id="environment">Environment</h3>
<p><strong>App version:</strong> 4.0.0</p>
<p><strong>Current URL:</strong> <a target="_blank"  href="https://www.eodashboard.org/explore?indicator=N3a2_TSM_esa&x=475481.24929&y=5319782.44383&z=4.36334">https://www.eodashboard.org/explore?indicator=N3a2_TSM_esa&amp;x=475481.24929&amp;y=5319782.44383&amp;z=4.36334</a></p>
<p><strong>Operating system:</strong> MacOS</p>
<p><strong>Affected browser:</strong> Chrome 128</p>
<h3 id="steps-to-reproduce">Steps to reproduce:</h3>
<p><a target="_blank"  href="https://www.eodashboard.org/explore?indicator=N3a2_TSM_esa&x=475481.24929&y=5319782.44383&z=4.36334">https://www.eodashboard.org/explore?indicator=N3a2_TSM_esa&amp;x=475481.24929&amp;y=5319782.44383&amp;z=4.36334</a></p>
<h3 id="expected-behaviour">Expected Behaviour:</h3>
<p>POI loads on the map</p>
<h3 id="contact-information-or-additional-comments-optional-publicly-visible">Contact information or additional comments (optional, publicly visible):</h3>
<p>anca</p>

**Comment by lubojr** [comment] 2024-09-10 07:16
STAC Collection had infinity characters: 

 [
          Infinity,
          Infinity,
          -Infinity,
          -Infinity
        ],
        [
          Infinity,
          Infinity,
          -Infinity,
          -Infinity
        ]

https://eodashcatalog.eox.at/eodash_catalog_0.0.32/trilateral/N3a2_total_suspended_matter_tri_esa/N3a2_total_suspended_matter_tri_esa/collection.json

**Comment by lubojr** [comment] 2024-09-10 08:02
@aapopescu The problem is two-fold.

There two POIs, which we were instructed to add to the configuration do not have any STAC Items and images in SH (https://github.com/eurodatacube/eodash-catalog/blob/main/collections/N3a2_total_suspended_matter_tri_esa.yaml#L40-L47).

However, if that happens, the catalog generator produces an invalid collection STAC json, which is something I am now going to fix (so that it instead produces a warning in the logs).

The question is just if that happens, if the eodash client should show the POI icon (and on clicking it, nothing will happen, as there are no dates to show) or if the POI should not even be there.

**Comment by lubojr** [comment] 2024-09-11 15:25
@dmoglioni @FedericoRondoni https://github.com/eurodatacube/eodash-catalog/blob/main/collections/N3a2_total_suspended_matter_tri_esa.yaml#L40-L47 These two POIs do not have any images for TSM, could you please double check and confirm if no images should be there and if that is true, remove these locations from the config? Thank you

**Comment by FedericoRondoni** [comment] 2024-09-24 09:36
@lubojr we are going to check it both on the bucket and from the original data source

**Comment by FedericoRondoni** [comment] 2024-10-02 14:27
@santilland we have solved this issue.
Now, everything should be visible.
You can find the updated yaml files at this link https://github.com/eurodatacube/eodash-catalog/pull/197

**Comment by santilland** [comment] 2024-10-28 10:36
With the updated catalog this is now working, closing issue, thanks all for the help!

**Closed by santilland** 2024-10-28 10:36 UTC
Labels: bug
