### ISSUE TITLE
Saving time selection does not work once dashboard was created

### ISSUE THREAD

**Issue by spectrachrome** [eurodatacube/eodash#1483] opened 2022-05-26 09:17 UTC
When there is already a saved dashboard, the save process when a different time is selected does not permanently change
the time selection. After a refresh, the old value comes back, which means the value is not saved correctly.

A short peek into the browser console reveals there is a validation error of some kind.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Firefox
 - Version 99.0.1

**Steps to reproduce**
Create and save a dashboard, open the dashboard with editing privileges, save time and refresh.

**Expected behaviour**
The time selection reflects the change after a refresh.

**Comment by lubojr** [comment] 2023-11-28 09:04
Duplicate of https://github.com/eurodatacube/eodash/issues/2341

**Closed by lubojr** 2023-11-28 09:04 UTC
Labels: bug
