### ISSUE TITLE
Link from eodashboard stories to Dashboard Not working

### ISSUE THREAD

**Issue by AlessandroScremin** [eurodatacube/eodash#2409] opened 2023-11-29 14:22 UTC
@lubojr @santilland cc: @aapopescu @dmoglioni 

Using Google Chome

I access the user story on cryosphere here:
https://eodashboard.org/story?id=esa-thwaites&page=5

when I click on one of the links in the EXPLORE Datasets, i'm addressed to the maps but with no data visible, all grey.

![image](https://github.com/eurodatacube/eodash/assets/65602207/47af0b0a-a669-4610-a8dd-7c0885378082)

Then if I look for the melmaps in the search panel i can visualisze at least the AOI

 
![image](https://github.com/eurodatacube/eodash/assets/65602207/9b2574a7-f8ec-4539-aeb1-8bc423f0f3cf)

could it be a possible issue with geographic coordinates set in the link in the explore datasets section of the story?

**Comment by lubojr** [comment] 2023-11-29 14:46
Thank you for the report. I will invest the issue.

**Comment by lubojr** [comment] 2023-11-29 23:16
I confirm that it was a problem on the previous production deployment. I have now done a new deployment and can not reproduce again. Could you please test as well @AlessandroScremin ? Thanks

**Comment by AlessandroScremin** [comment] 2023-11-30 13:12
@lubojr 

same issue. I tried with chrome normal mode and also incognito...but got the same grey page...

![image](https://github.com/eurodatacube/eodash/assets/65602207/3188a68b-0259-4d4d-adc5-7f331c47f561)

**Comment by lubojr** [comment] 2023-12-01 11:05
Oh no. I shall try to reproduce again then.

**Comment by lubojr** [comment] 2023-12-05 15:12
@AlessandroScremin Could you please try in an anonymous window?

**Comment by lubojr** [comment] 2024-04-29 10:47
This seems to be now fixed with the transition to the STAC based loading of datasets.

**Closed by lubojr** 2024-04-29 10:47 UTC
Labels: bug
