### ISSUE TITLE
It seems NASA endpoint is down

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#440] opened 2020-08-06 08:29 UTC
https://8ib71h0627.execute-api.us-east-1.amazonaws.com/
The endpoint for EO data requests is returning "Internal server error" 500 for all requests

**Comment by olafveerman** [comment] 2020-08-06 10:05
Thanks for the report @santilland 
We've identified the issue and are working to bring the API back up. We'll work on a more detailed report once the API is back up.

**Comment by olafveerman** [comment] 2020-08-06 10:07
The API is back up @santilland . Keeping this issue open to provide more info later today.

**Comment by drewbo** [comment] 2020-08-06 15:39
@santilland here is our post-mortem analysis of the error which is fully resolved:

# NASA-COVID API Outage, August 5th-6th
## Issue Summary
We added a new dependency to the API to support Planet imagery mosaicking. The dependency is included in the local development environment and the CI test environment but isn't present in the bundled lambda function. When new requests were made against the deployed API, they failed with HTTP 500 errors. The CloudWatch logs show: `Runtime.ImportModuleError: Unable to import module 'handler': No module named 'requests'`.

## Timeline

August 5, 21:03 UTC - Erroring commit merged to master (tests passing)  
August 6, 07:28 UTC - ESA notifies Development Seed of HTTP 500 errors  
August 6, 09:27 UTC - Development Seed begin investigation into the error  
August 6, 10:08 UTC - Development Seed reverts erroring commit and redploys the API, resolving the issue

## Root Cause
The new [Planet imagery mosaicking feature](https://github.com/NASA-IMPACT/covid-api/pull/43) requires the popular [`requests`](https://requests.readthedocs.io/en/master/) library. While adding the feature, we didn't add the dependency to the [required packages](https://github.com/NASA-IMPACT/covid-api/blob/master/setup.py#L8-L20) because it was already present in his local development environment. In general, this error will be caught during the continuous integration testing on CircleCI. In this case, the missing dependency didn't fail on CircleCI or local testings because `requests` is [specifically added for testing purposes](https://github.com/NASA-IMPACT/covid-api/blob/master/setup.py#L37). This created a fairly unique situation where the tests were able to pass because the dependency was present but the library was not included in the deployed lambda function which runs the API.

## Resolution and recovery
After notification of the error, we parsed the AWS CloudWatch logs to find the relevant error:

> `Runtime.ImportModuleError: Unable to import module 'handler': No module named 'requests'`

We resolved the error by [reverting the aforementioned commit](https://github.com/NASA-IMPACT/covid-api/pull/44). The deployment was delayed because of [npm registry errors](https://twitter.com/npmstatus/status/1291296875572629504) which prevented AWS CDK from being installed.

## Corrective and Preventative Measures
`requests` is the only non-test library installed in the test environment, so errors of the same variety (tests pass with a failing import and API-level syntax error) are unlikely to occur. [API Monitoring](https://github.com/NASA-IMPACT/covid-api/issues/38) will be prioritized for faster notification of these errors.

**Comment by santilland** [comment] 2020-08-06 15:54
Thank you for the nicely compiled information!
All clear on my side, i think we can close the issue.

**Closed** 2020-08-06 16:42 UTC
Labels: bug, critical
